name: 'Telegram Notifier Action'
description: 'Sends message if enabled in config'
inputs:
  message:
    required: true
  telegram_token:
    required: true
  telegram_chat_id:
    required: true
  telegram_topic_id:
    required: false
  config_branch:
    required: false
    default: 'master'
  # Новый флаг принудительной отправки
  force_send:
    description: 'Bypass config check and send message anyway'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Check if notification is enabled
      id: check_status
      shell: bash
      run: |
        ENABLED="false"

        # Если включен форсированный режим - сразу ставим true
        if [[ "${{ inputs.force_send }}" == "true" ]]; then
          echo "Force send enabled. Ignoring config file."
          ENABLED="true"
        else
          # Иначе проверяем файл в указанной ветке
          CONTENT=$(git show origin/${{ inputs.config_branch }}:.github/telegram-enabled.txt 2>/dev/null || echo "")
          if [ -n "$CONTENT" ]; then
            VALUE=$(echo "$CONTENT" | grep -v '^#' | grep -v '^[[:space:]]*$' | head -n 1 | xargs | tr '[:upper:]' '[:lower:]')
            if [[ "$VALUE" == "1" || "$VALUE" == "true" || "$VALUE" == "on" ]]; then
              ENABLED="true"
            fi
          fi
        fi
        
        echo "is_enabled=$ENABLED" >> $GITHUB_OUTPUT

    - name: Send Message
      if: steps.check_status.outputs.is_enabled == 'true'
      shell: bash
      run: |
        MSG_TEXT=$(echo "${{ inputs.message }}" | jq -aRs .)
        URL="https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage"
        TOPIC_ID="${{ inputs.telegram_topic_id }}"
        
        if [ -z "$TOPIC_ID" ]; then
          curl -s -X POST "$URL" -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"${{ inputs.telegram_chat_id }}\", \"text\": $MSG_TEXT, \"parse_mode\": \"HTML\"}"
        else
          curl -s -X POST "$URL" -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"${{ inputs.telegram_chat_id }}\", \"message_thread_id\": \"$TOPIC_ID\", \"text\": $MSG_TEXT, \"parse_mode\": \"HTML\"}"
        fi
